#!/usr/bin/env ruby
# This script generates the TSV imported into Script objects from the seed:scripts rake task.
# Input is via ARGF (takes filename or standard input), output is printed to standard output.
require 'yaml'

$stage = nil
$concepts = []
$skin = nil
$hash = {}
$script_name

def stage(name)
  $stage = name
  $concepts = []
  $skin = nil
end

def concepts(*items)
  $concepts = items
end

def skin(name)
  $skin = name
end

def level(name)
  puts [$stage, $concepts.join(','), name].join("\t")
end

puts %w(Stage Concepts Name).join("\t")
eval ARGF.read
